#ifndef CP_BOII__TEXT_BUFFER_COMMANDS
#define CP_BOII__TEXT_BUFFER_COMMANDS

#pragma once

typedef enum class Command
{
  BACKSPACE,
  ENTER,
  INSERT_CHAR,
  INSERT_STRING,
  NEW_LINE,
  MOVE_CURSOR_BACK,
  MOVE_CURSOR_UP,
  MOVE_CURSOR_FORWARD,
  MOVE_CURSOR_DOWN,
  MOVE_CURSOR_TO_HOME,
  MOVE_CURSOR_TO_END,
  MOVE_CURSOR_TO_BUFFER_START,
  MOVE_CURSOR_TO_BUFFER_END
} Command;

#endif